name: vuepress deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Install and build
      run: |
        npm install
        npm run docs:build
    - name: Deploy built filed
      env: 
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        cd docs/.vuepress/dist
        git config --global user.email "ckm0728wash@gmail.com"
        git config --global user.name "KimWash"
        git init
        git add -A
        git commit -m "deploy"
        https://${TOKEN}@github.com/KimWash/kimwash.github.io.git master:gh-pages
